# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Uncomment this line if you're using Swift
use_frameworks!

def shared_pods
    pod 'Alamofire', '~> 3.0'
    pod 'AlamofireImage', '~> 2.2.0'
    pod 'SwiftyJSON', '~> 2.3.1'
    pod 'RealmSwift', '~> 0.98'
end

target 'GardenToGarden' do
	shared_pods
end

target 'GardenToGardenTests' do
	shared_pods
end

target 'GardenToGardenUITests' do
	shared_pods
end

